-- Seed sample properties for OdiBrix
INSERT INTO properties (title, description, property_type, status, price, area_sqft, bedrooms, bathrooms, location, address, amenities, featured) VALUES
(
  'Luxurious 3BHK Villa - Sunrise Enclave',
  'Experience modern living in this beautifully designed 3BHK villa featuring premium finishes, spacious interiors, and a private garden. Perfect for families seeking comfort and elegance.',
  'villa',
  'available',
  8500000,
  2200,
  3,
  3,
  'Bhubaneswar, Odisha',
  'Plot 45, Sunrise Enclave, Patia, Bhubaneswar',
  ARRAY['Modular Kitchen', 'Private Garden', 'Car Parking', 'Security System', '24/7 Water Supply', 'Power Backup'],
  true
),
(
  'Premium 2BHK Apartment - City Heights',
  'Contemporary 2BHK apartment in the heart of the city with stunning views, modern amenities, and excellent connectivity to IT hubs and commercial centers.',
  'apartment',
  'available',
  4500000,
  1150,
  2,
  2,
  'Bhubaneswar, Odisha',
  'Tower B, City Heights, Chandrasekharpur, Bhubaneswar',
  ARRAY['Swimming Pool', 'Gym', 'Club House', 'Children Play Area', 'Covered Parking', 'Lift'],
  true
),
(
  'Commercial Space - Business Park',
  'Prime commercial space ideal for offices, showrooms, or retail outlets. Located in a high-traffic business district with excellent visibility and parking facilities.',
  'commercial',
  'available',
  12000000,
  3500,
  NULL,
  2,
  'Bhubaneswar, Odisha',
  'Unit 12, Business Park, Jaydev Vihar, Bhubaneswar',
  ARRAY['Central AC', 'Conference Room', 'Cafeteria', 'Ample Parking', 'Generator Backup', 'High-Speed Internet Ready'],
  true
),
(
  'Residential Plot - Green Valley',
  'Premium residential plot in a gated community with all modern infrastructure. Ideal for building your dream home surrounded by nature.',
  'plot',
  'available',
  3200000,
  2400,
  NULL,
  NULL,
  'Bhubaneswar, Odisha',
  'Plot 78, Green Valley Township, Jatni Road, Bhubaneswar',
  ARRAY['Gated Community', 'Wide Roads', 'Underground Drainage', 'Street Lights', 'Park Access', 'Temple Nearby'],
  false
),
(
  'Elegant Farmhouse - Countryside Retreat',
  'Escape to this serene farmhouse offering 1 acre of lush greenery, organic farm, swimming pool, and modern living spaces. Perfect weekend getaway or permanent residence.',
  'farmhouse',
  'available',
  25000000,
  5000,
  4,
  4,
  'Khordha, Odisha',
  'Survey 234, Countryside Retreat, Khordha District',
  ARRAY['Swimming Pool', 'Organic Farm', 'Servant Quarter', 'Bore Well', 'Fruit Orchard', 'Guest House'],
  true
),
(
  'Compact 1BHK Apartment - Metro View',
  'Affordable yet stylish 1BHK apartment perfect for young professionals or couples. Modern design with efficient space utilization and great connectivity.',
  'apartment',
  'available',
  2800000,
  650,
  1,
  1,
  'Bhubaneswar, Odisha',
  'Block C, Metro View Residency, Nayapalli, Bhubaneswar',
  ARRAY['Gym', 'Security', 'Covered Parking', 'Lift', 'Power Backup', 'Near Metro Station'],
  false
);
